use crate::ServerError;
use crate::SockAddr;
use crate::close;
use crate::read;
use crate::ReadError;

unsafe extern "C" {
    // File control -> fcntl() provides for control over descriptors.  The argument fildes is a
    // descriptor to be operated on by cmd. In particular, the C version supports variadic
    // arguments, but for our purposes, we only need 1 argument because we only want to set the
    // flags with F_SETFL and F_GETFL. In the case of F_GETFL, the `value` argument is ignored.
    fn fcntl(filedes: i32, cmd: i32, value: i32) -> i32;
    // poll() examines a set of file descriptors to see if some of them are ready for I/O or if
    // certain events have occurred on them.  The fds argument is a pointer to an array of pollfd
    // structures, as defined in this file and in ⟨poll.h⟩.  The nfds argument specifies the size of
    // the fds array.
    // Also referred to as `the readiness API`.
    // If timeout is greater than zero, it specifies a maximum interval (in milliseconds) to wait
    // for any file descriptor to become ready.  If timeout is zero, then poll() will return
    // without blocking. If the value of timeout is -1, the poll blocks indefinitely.
    //
    // poll() returns the number of descriptors that are ready for I/O, or -1 if an error occurred.
    // If the time limit expires, poll() returns 0.  If poll() returns with an error, including one
    // due to an interrupted call, the fds array will be unmodified and the global variable errno
    // will be set to indicate the error
    fn poll(fds: *mut PollFd, nfds: u32, timeout: i32) -> i32;
    // Note: Should also define `kqueue` which is used for real projects in BSD
    // Note: For file IO within an event loop, we should use io_uring
}

mod cmd {
    //! File control commands
    // Get file control flags.
    pub const F_GETFL: i32 = 3;
    // Set file control flags.
    pub const F_SETFL: i32 = 3;
}

mod fd_flags {
    //! File status flags. These are used by open(2) and fcntl(2)
    // No delay.
    // Note: Setting this to i32 feels a bit idiotic
    pub const O_NONBLOCK: i32 = 0x0000_0004;
}

// Set the file descriptor `fd` as non blocking
fn set_nonblock(fd: i32) -> Result<(), std::io::Error> {
    let mut flags = unsafe { fcntl(fd, cmd::F_GETFL, 0) };

    crate::check_status(flags)?;
    flags |= fd_flags::O_NONBLOCK;
    let status = unsafe { fcntl(fd, cmd::F_SETFL, flags) };
    crate::check_status(status)?;
    Ok(())
}

mod poll_flags {
    // Any readable data available
    pub const POLLIN: u16 = 0x0001;
    // File descriptor is writable
    pub const POLLOUT: u16 = 0x0004;
    /*
     * These events are set if they occur regardless of whether they were
     * requested.
     */
    // Some poll error occured
    pub const POLLERR: u16 = 0x0008;
    // File descriptor was "hung up"
    pub const POLLHUP: u16 = 0x0010;
    // Requested events "invalid"
    pub const POLLNVAL: u16 = 0x0020;
}

#[derive(Debug)]
#[repr(C)]
struct PollFd {
    // File descriptor to poll
    fd: u32,
    // Events to look for. Requests for wanting to read, write or both.
    // Note: Should we make this of type PollFlags?
    events: u16,
    // Events returned, which may occur or have occured. Uses the same set of flags to indicate
    // whether the `fd` is capable to `read` and / or `write`
    // Note: Should we make this of type PollFlags?
    revents: u16,
}

impl PollFd {
    pub fn new(fd: u32, events: u16, revents: u16) -> Self {
        Self {
            fd,
            events,
            revents,
        }
    }
}

// Represents per-connection state of a socket used by the event loop of  the application
#[derive(Default)]
struct Conn {
    fd: i32,
    // Application's intention, for the event loop
    // `want_read` and `want_write` represents the fd list for the readiness API. In other words,
    // when the event loop polls this connection for the state, these values tell the event loop
    // what it is desired by this `fd` connection.
    want_read: bool,
    want_write: bool,
    // Tells the event loop to destroy the connection
    want_close: bool,

    // Buffered input and output
    // Data to be parsed by the application. This storage buffers data from the socket for the
    // protocol parser to work on.
    incoming: Vec<u8>,
    // Responses generated by the application. This storage buffer generated responses that are
    // written to the socket.
    outgoing: Vec<u8>,
}

fn run_server(fd: i32) -> Result<(), ServerError> {
    use poll_flags::*;
    // 1. Construct the `fd` list for `poll` function to use

    // A map of all client connections, keyed by fd. An fd is allocated as the smallest available
    // non-negative integer, so the mapping from fd to the `Conn` state can be a flat array indexed
    // by fd.
    let mut fd2conn: Vec<Option<Conn>> = vec![];
    // We want to construct this array in order to fill `poll` with it as an arg
    let mut poll_args: Vec<PollFd> = vec![];

    // Create the listening socket for the server -> create, set it reuse, bind, listen
    let fd = crate::setup_socket()?;
    // Set the listening socket as non-blocking
    set_nonblock(fd)?;

    loop {
        // Clear the arguments for poll
        poll_args.clear();

        // TODO: Check fd is not -1
        // Put the listening sockets in the first position. This is the socket that we bind to our
        // server uses to accept new connections.
        let poll_read = PollFd::new(fd as u32, POLLIN, 0);
        poll_args.push(poll_read);
        // The rest are connection sockets
        for maybe_conn in fd2conn.iter_mut() {
            let Some(conn) = maybe_conn else {
                continue;
            };
            // TODO: Check fd is not -1
            let mut poll_fd = PollFd::new(conn.fd as u32, POLLERR, 0);

            // poll() flags from the application's intent
            if conn.want_read {
                poll_fd.events |= POLLIN;
            }
            if conn.want_write {
                poll_fd.events |= POLLOUT;
            }
            poll_args.push(poll_fd);
        }

        // 2. Wait for file descriptor readiness using `poll` syscall
        // TODO: Maybe we can try a timeout and retry afterwards.
        let poll_status = unsafe { poll(poll_args.as_mut_ptr(), poll_args.len() as u32, -1) };

        match crate::check_status(poll_status) {
            Ok(_ready_fds) => {}
            Err(err) => {
                // If this syscall was interrupted, it was due to a Unix signal. This is not an
                // error, but rather a way for the OS to let us know the syscall was interrupted.
                // In this case we would like to retry it.
                if err.kind() == std::io::ErrorKind::Interrupted {
                    continue;
                } else {
                    return Err(ServerError::StdIOError(err));
                }
            }
        }

        // 3. Handle the listening socket
        // If the listening socket returns, we are ready to accept new connection as the server.
        // accept is treated as read in readiness notifications.
        // TODO: make this safe. get(0) and check for errors
        if poll_args[0].revents & POLLIN != 0 {
            //
            if let Ok(conn) = handle_accept(fd) {
                // Put it in the map
                fd2conn.push(Some(conn));
            }
        } else {
            println!("{:x}", poll_args[0].revents);
        }

        // 4. Handle connection sockets. Sockets which are already connected from other clients
        for poll_fd in poll_args.iter().skip(1) {
            // TODO: make it safe -> get and try_from
            let mut maybe_conn = fd2conn[poll_fd.fd as usize].take();

            if let Some(mut conn) = maybe_conn {
                if poll_fd.revents & POLLIN != 0 {
                    handle_read(&mut conn)?;
                }
                if poll_fd.revents & POLLOUT != 0 {
                    handle_write(&conn)?;
                }
                // Close the socket or error or based on application request if it wants to close
                // the connection.
                // TODO: In case of an error, create a `handle_err`
                if (poll_fd.revents & POLLERR != 0) || conn.want_close {
                    let status = unsafe { close(conn.fd) };
                    // TODO: These should be logged to avoid crashing the whole application.
                    crate::check_status(status)?;
                } else {
                    fd2conn[poll_fd.fd as usize].replace(conn);
                }
            }
        }
    }
}

fn handle_accept(fd: i32) -> Result<Conn, ServerError> {
    // Handling accept of an incoming connection to the listening socket
    // TODO: Create a socket.rs module
    let mut client_sock_addr = SockAddr::default();
    let mut sock_addr_len: u32 = u32::try_from(core::mem::size_of::<SockAddr>())?;

    let conn_fd = unsafe { crate::accept(fd, &mut client_sock_addr, &mut sock_addr_len) };

    crate::check_status(conn_fd)?;
    println!("Client sock addr: {:?}", client_sock_addr);
    // Set the new connection fd to nonblocking mode
    set_nonblock(conn_fd)?;

    // Read the first request and return a connection state
    let conn = Conn {
        fd: conn_fd,
        want_read: true,
        ..Conn::default()
    };
    Ok(conn)
}

fn handle_read(conn: &mut Conn) -> Result<(), ServerError> {
    // Is the size too much? Should we tone it down?

    // 1. Do a non-blocking read.
    let mut buf = [0; 64 * 1024];
    let bread = unsafe {
        read(conn.fd, buf.as_mut_ptr() as *mut core::ffi::c_void, u32::try_from(buf.len())?)
    };

    if bread <= 0 {
        conn.want_close = true;
        return Ok(());
    }
    let bread = usize::try_from(bread)?;

    // 2. Add new data to the `incoming` buffer.
    conn.incoming.extend_from_slice(buf.get(0..bread).ok_or(ReadError::InvalidRange(0, bread))?);

    Ok(())
}

fn handle_write(conn: &Conn) -> Result<(), ServerError> {
    Ok(())
}
