unsafe extern "C" {
    // File control -> fcntl() provides for control over descriptors.  The argument fildes is a
    // descriptor to be operated on by cmd. In particular, the C version supports variadic
    // arguments, but for our purposes, we only need 1 argument because we only want to set the
    // flags with F_SETFL and F_GETFL. In the case of F_GETFL, the `value` argument is ignored.
    fn fcntl(filedes: i32, cmd: i32, value: i32) -> i32;
    // poll() examines a set of file descriptors to see if some of them are ready for I/O or if
    // certain events have occurred on them.  The fds argument is a pointer to an array of pollfd
    // structures, as defined in this file and in ⟨poll.h⟩.  The nfds argument specifies the size of
    // the fds array.
    // Also referred to as `the readiness API`.
    // If timeout is greater than zero, it specifies a maximum interval (in milliseconds) to wait
    // for any file descriptor to become ready.  If timeout is zero, then poll() will return
    // without blocking. If the value of timeout is -1, the poll blocks indefinitely.
    fn poll(fds: &mut PollFd, nfds: u32, timeout: i32) -> i32;
    // Note: Should also define `kqueue` which is used for real projects in BSD
    // Note: For file IO within an event loop, we should use io_uring
}

mod cmd {
    //! File control commands
    // Get file control flags.
    pub const F_GETFL: i32 = 3;
    // Set file control flags.
    pub const F_SETFL: i32 = 3;
}

mod fd_flags {
    //! File status flags. These are used by open(2) and fcntl(2)
    // No delay.
    // Note: Setting this to i32 feels a bit idiotic
    pub const O_NONBLOCK: i32 = 0x0000_0004;
}

// Set the file descriptor `fd` as non blocking
fn set_nonblock(fd: i32) -> Result<(), std::io::Error> {
    let mut flags = unsafe { fcntl(fd, cmd::F_GETFL, 0) };

    crate::check_status(flags)?;
    flags |= fd_flags::O_NONBLOCK;
    let status = unsafe { fcntl(fd, cmd::F_SETFL, flags) };
    crate::check_status(status)?;
    Ok(())
}

mod poll_flags {
    // Any readable data available
    pub const POLLIN: u16 = 0x0001;
    // File descriptor is writable
    pub const POLLOUT: u16 = 0x0004;
    /*
     * These events are set if they occur regardless of whether they were
     * requested.
     */
    // Some poll error occured
    pub const POLLERR: u16 = 0x0008;
    // File descriptor was "hung up"
    pub const POLLHUP: u16 = 0x0010;
    // Requested events "invalid"
    pub const POLLNVAL: u16 = 0x0020;
}

#[derive(Debug)]
#[repr(C)]
struct PollFd {
    // File descriptor to poll
    fd: u32,
    // Events to look for. Requests for wanting to read, write or both.
    // Note: Should we make this of type PollFlags?
    events: u16,
    // Events returned, which may occur or have occured. Uses the same set of flags to indicate
    // whether the `fd` is capable to `read` and / or `write`
    // Note: Should we make this of type PollFlags?
    revents: u16,
}

impl PollFd {
    pub fn new(fd: u32, events: u16, revents: u16) -> Self {
        Self { fd, events, revents }
    }
}

// Represents per-connection state of a socket used by the event loop of  the application
struct Conn {
    fd: i32,
    // Application's intention, for the event loop
    // `want_read` and `want_write` represents the fd list for the readiness API. In other words,
    // when the event loop polls this connection for the state, these values tell the event loop
    // what it is desired by this `fd` connection.
    want_read: bool,
    want_write: bool,
    // Tells the event loop to destroy the connection
    want_close: bool,

    // Buffered input and output
    // Data to be parsed by the application. This storage buffers data from the socket for the
    // protocol parser to work on.
    incoming: Vec<u8>,
    // Responses generated by the application. This storage buffer generated responses that are
    // written to the socket.
    outgoing: Vec<u8>,
}

fn run_app(fd: i32) {
    use poll_flags::*;
    // 1. Construct the `fd` list for `poll` function to use

    // A map of all client connections, keyed by fd. An fd is allocated as the smallest available
    // non-negative integer, so the mapping from fd to the `Conn` state can be a flat array indexed
    // by fd.
    let mut fd2conn: Vec<Option<Conn>> = vec![];
    // We want to construct this array in order to fill `poll` with it as an arg
    let mut poll_args: Vec<PollFd> = vec![];

    loop {
        // Clear the arguments for poll
        poll_args.clear();

        // TODO: Check fd is not -1
        // Put the listening (reading) sockets in the first position
        let poll_read = PollFd::new(fd as u32, POLLIN, 0);
        poll_args.push(poll_read);
        // The rest are connection sockets
        for maybe_conn in fd2conn.iter_mut() {
            let Some(conn) = maybe_conn else {
                continue;
            };
            // TODO: Check fd is not -1
            let mut poll_fd = PollFd::new(conn.fd as u32, POLLERR, 0);

            // poll() flags from the application's intent
            if conn.want_read {
                poll_fd.events |= POLLIN;
            }
            if conn.want_write {
                poll_fd.events |= POLLOUT;
            }
            poll_args.push(poll_fd);
        }
    }
}

