use crate::ReadError;
use crate::ServerError;
use crate::SockAddr;
use crate::close;
use crate::read;
use crate::write;

use std::collections::BTreeMap;

// Max buffer size (allegedly) allowed by the xnu kernel (aka BIG_PIPE_SIZE)
const MAX_KERNEL_PIPE_SIZE: usize = 32 << 20;
const MAX_CMD_ARGS: usize = 100;

unsafe extern "C" {
    // File control -> fcntl() provides for control over descriptors.  The argument fildes is a
    // descriptor to be operated on by cmd. In particular, the C version supports variadic
    // arguments, but for our purposes, we only need 1 argument because we only want to set the
    // flags with F_SETFL and F_GETFL. In the case of F_GETFL, the `value` argument is ignored.
    fn fcntl(filedes: i32, cmd: i32, value: i32) -> i32;
    // poll() examines a set of file descriptors to see if some of them are ready for I/O or if
    // certain events have occurred on them.  The fds argument is a pointer to an array of pollfd
    // structures, as defined in this file and in ⟨poll.h⟩.  The nfds argument specifies the size of
    // the fds array.
    // Also referred to as `the readiness API`.
    // If timeout is greater than zero, it specifies a maximum interval (in milliseconds) to wait
    // for any file descriptor to become ready.  If timeout is zero, then poll() will return
    // without blocking. If the value of timeout is -1, the poll blocks indefinitely.
    //
    // poll() returns the number of descriptors that are ready for I/O, or -1 if an error occurred.
    // If the time limit expires, poll() returns 0.  If poll() returns with an error, including one
    // due to an interrupted call, the fds array will be unmodified and the global variable errno
    // will be set to indicate the error
    fn poll(fds: *mut PollFd, nfds: u32, timeout: i32) -> i32;
    // Note: Should also define `kqueue` which is used for real projects in BSD
    // Note: For file IO within an event loop, we should use io_uring
}

mod cmd {
    //! File control commands
    // Get file control flags.
    pub const F_GETFL: i32 = 3;
    // Set file control flags.
    pub const F_SETFL: i32 = 3;
}

mod fd_flags {
    //! File status flags. These are used by open(2) and fcntl(2)
    // No delay.
    // Note: Setting this to i32 feels a bit idiotic
    pub const O_NONBLOCK: i32 = 0x0000_0004;
}

// Set the file descriptor `fd` as non blocking
fn set_nonblock(fd: i32) -> Result<(), std::io::Error> {
    let mut flags = unsafe { fcntl(fd, cmd::F_GETFL, 0) };

    crate::check_status(flags)?;
    flags |= fd_flags::O_NONBLOCK;
    let status = unsafe { fcntl(fd, cmd::F_SETFL, flags) };
    crate::check_status(status)?;
    Ok(())
}

mod poll_flags {
    // Any readable data available
    pub const POLLIN: u16 = 0x0001;
    // File descriptor is writable
    pub const POLLOUT: u16 = 0x0004;
    /*
     * These events are set if they occur regardless of whether they were
     * requested.
     */
    // Some poll error occured
    pub const POLLERR: u16 = 0x0008;
    // File descriptor was "hung up"
    pub const POLLHUP: u16 = 0x0010;
    // Requested events "invalid"
    pub const POLLNVAL: u16 = 0x0020;
}

#[derive(Debug)]
#[repr(C)]
struct PollFd {
    // File descriptor to poll
    fd: u32,
    // Events to look for. Requests for wanting to read, write or both.
    // Note: Should we make this of type PollFlags?
    events: u16,
    // Events returned, which may occur or have occured. Uses the same set of flags to indicate
    // whether the `fd` is capable to `read` and / or `write`
    // Note: Should we make this of type PollFlags?
    revents: u16,
}

impl PollFd {
    pub fn new(fd: u32, events: u16, revents: u16) -> Self {
        Self {
            fd,
            events,
            revents,
        }
    }
}

// Represents per-connection state of a socket used by the event loop of  the application
#[derive(Default, Debug)]
struct Conn {
    fd: u32,
    // Application's intention, for the event loop
    // `want_read` and `want_write` represents the fd list for the readiness API. In other words,
    // when the event loop polls this connection for the state, these values tell the event loop
    // what it is desired by this `fd` connection.
    want_read: bool,
    want_write: bool,
    // Tells the event loop to destroy the connection
    want_close: bool,

    // Buffered input and output
    // Data to be parsed by the application. This storage buffers data from the socket for the
    // protocol parser to work on.
    incoming: Vec<u8>,
    // Responses generated by the application. This storage buffer generated responses that are
    // written to the socket.
    // Currently this approach is not great as removing data from the front performs a reallocation
    // for each message. Something like a circular buffer with message checking would be better.
    outgoing: Vec<u8>,
}

pub fn run_server() -> Result<(), ServerError> {
    use poll_flags::*;
    // 1. Construct the `fd` list for `poll` function to use

    // A map of all client connections, keyed by fd. An fd is allocated as the smallest available
    // non-negative integer, so the mapping from fd to the `Conn` state can be a flat array indexed
    // by fd.
    let mut fd2conn: Vec<Option<Conn>> = vec![];
    // The first 3 file descripors are reserved by the system as follow:
    // - stdin: 0
    // - stdout: 1
    // - stderr: 2
    // The forth file descriptor is the listening socket of this server that accepts new
    // connections.
    // As such we are populating the connections with placeholder values
    for _ in 0..4 {
        fd2conn.push(None);
    }
    // We want to construct this array in order to fill `poll` with it as an arg
    let mut poll_args: Vec<PollFd> = vec![];

    // Create the listening socket for the server -> create, set it reuse, bind, listen
    let fd = crate::setup_socket()?;
    // Set the listening socket as non-blocking
    set_nonblock(fd)?;

    let mut g_data = BTreeMap::<String, String>::new();

    loop {
        // Clear the arguments for poll
        poll_args.clear();

        // Put the listening sockets in the first position. This is the socket that we bind to our
        // server to listen for new connections. Because accept acts as a read, we are telling poll
        // to notify us when this particular socket is ready to be read
        let poll_read = PollFd::new(fd.try_into()?, POLLIN, 0);
        poll_args.push(poll_read);

        // The rest of the sockets we want to get readiness information for are connected sockets
        for maybe_conn in fd2conn.iter_mut() {
            let Some(conn) = maybe_conn else {
                continue;
            };
            // We want to know if there are any errors
            let mut poll_fd = PollFd::new(conn.fd, POLLERR, 0);

            // We also want to know if the sockets of the connections are ready to be read or wrote
            // depending on the current state of the connection in the event loop.
            if conn.want_read {
                poll_fd.events |= POLLIN;
            }
            if conn.want_write {
                poll_fd.events |= POLLOUT;
            }
            // Another fd ready to be polled
            poll_args.push(poll_fd);
        }

        // 2. Wait for file descriptor readiness using `poll` syscall
        let poll_status = unsafe { poll(poll_args.as_mut_ptr(), poll_args.len().try_into()?, -1) };

        match crate::check_status(poll_status) {
            Ok(_ready_fds) => {}
            Err(err) => {
                // If this syscall was interrupted, it was due to a Unix signal. This is not an
                // error, but rather a way for the OS to let us know the syscall was interrupted.
                // In this case we would like to retry it.
                if err.kind() == std::io::ErrorKind::Interrupted {
                    continue;
                } else {
                    return Err(ServerError::StdIOError(err));
                }
            }
        }

        // 3. Handle the listening socket
        // If the listening socket returns, we are ready to accept new connection as the server.
        // `accept` is treated as `read` in readiness notifications
        let listening_poll_fd = poll_args.get(0).ok_or(ReadError::InvalidIdx(0))?;
        if listening_poll_fd.revents & POLLIN != 0 {
            if let Ok(conn) = handle_accept(fd) {
                let conn_idx = usize::try_from(conn.fd)?;
                // If we already had place for this descriptor from a previously closed connection,
                // we are reusing that.
                if conn_idx < fd2conn.len() {
                    fd2conn[conn_idx].replace(conn);
                } else {
                    // Put it in the map
                    fd2conn.push(Some(conn));
                }
            }
        } else {
            println!("{:x}", listening_poll_fd.revents);
        }

        // 4. Handle connection sockets. Sockets which are already connected from other clients
        for poll_fd in poll_args.iter().skip(1) {
            // We get the connection at the index of the fd
            let conn_idx = usize::try_from(poll_fd.fd)?;
            let mut maybe_conn = fd2conn
                .get_mut(conn_idx)
                .ok_or(ReadError::InvalidIdx(conn_idx))?
                .take();

            if let Some(mut conn) = maybe_conn {
                // Read or write based on readiness. Should we check for want_read and want_write?
                if poll_fd.revents & POLLIN != 0 {
                    handle_read(&mut conn, &mut g_data)?;
                }
                if poll_fd.revents & POLLOUT != 0 {
                    handle_write(&mut conn)?;
                }
                // Close the socket or error or based on application request if it wants to close
                // the connection.
                // TODO: In case of an error, create a `handle_err`
                if (poll_fd.revents & POLLERR != 0) || conn.want_close {
                    let status = unsafe { close(i32::try_from(conn.fd)?) };
                    // TODO: These should be logged to avoid crashing the whole application.
                    crate::check_status(status)?;
                } else {
                    fd2conn
                        .get_mut(conn_idx)
                        .ok_or(ReadError::InvalidIdx(conn_idx))?
                        .replace(conn);
                }
            } else {
                println!("Missing fd {:x?}", poll_fd);
            }
        }
    }
}

fn handle_accept(fd: i32) -> Result<Conn, ServerError> {
    // Handling accept of an incoming connection to the listening socket
    // TODO: Create a socket.rs module
    let mut client_sock_addr = SockAddr::default();
    let mut sock_addr_len: u32 = u32::try_from(core::mem::size_of::<SockAddr>())?;

    let conn_fd = unsafe { crate::accept(fd, &mut client_sock_addr, &mut sock_addr_len) };

    crate::check_status(conn_fd)?;
    println!("Client sock addr: {:?}", client_sock_addr);
    // Set the new connection fd to nonblocking mode in order to be polled
    set_nonblock(conn_fd)?;

    // Read the first request and return a connection state
    let conn = Conn {
        fd: u32::try_from(conn_fd)?,
        want_read: true,
        ..Conn::default()
    };
    Ok(conn)
}

fn handle_read(conn: &mut Conn, g_data: &mut BTreeMap<String, String>) -> Result<(), ServerError> {
    // Is the size too much? Should we tone it down?
    // 1. Do a non-blocking read.
    let mut buf = [0; 1024];
    let bread = unsafe {
        read(
            conn.fd.try_into()?,
            buf.as_mut_ptr() as *mut core::ffi::c_void,
            u32::try_from(buf.len())?,
        )
    };

    if bread <= 0 {
        conn.want_close = true;
        return Ok(());
    }
    let bread = usize::try_from(bread)?;

    // 2. Add new data to the `incoming` buffer.
    conn.incoming
        .extend_from_slice(buf.get(0..bread).ok_or(ReadError::InvalidRange(0, bread))?);

    // Try to process the data in one request
    while try_one_request(conn, g_data)? {}

    // Update the readiness intention
    if conn.outgoing.len() > 0 {
        conn.want_read = false;
        conn.want_write = true;
        // We can assume the client socket is likely to read a response after sending a request,
        // so we do not have to wait for the next iteration to write to it.
        // This assumption is false with a pipeline client which does not read while the server
        // is writing.

        // Optimistic non-blocking writes
        return handle_write(conn);
    }

    Ok(())
}

#[derive(Debug)]
pub enum ParseError {
    TooManyArgs(usize),
    TrailingGarbage,
    ReadError(ReadError),
    TryFromIntError(std::num::TryFromIntError),
}

impl From<ReadError> for ParseError {
    fn from(err: ReadError) -> Self {
        Self::ReadError(err)
    }
}

impl From<std::num::TryFromIntError> for ParseError {
    fn from(err: std::num::TryFromIntError) -> Self {
        Self::TryFromIntError(err)
    }
}

// Parses a client request of the form
// | nstr | len1 | str1 | len2 | str2 | ... | len_nstr | str_nstr |
// 0      4      8     8+len1
//
// - nstr is a 4 byte little endian unsigned integer with the number of items in the list
fn parse_req(request: &[u8]) -> Result<Vec<String>, ParseError> {
    // Cursor where we read from for request
    let mut idx = 0usize;
    // Read the number of cmd components
    let n_args = usize::try_from(read_u32_le(request, idx)?)?;
    let size_of_u32 = core::mem::size_of::<u32>();
    idx = idx.saturating_add(size_of_u32);

    if n_args > MAX_CMD_ARGS {
        return Err(ParseError::TooManyArgs(n_args));
    }

    let mut args = vec![];

    // While we still have to process command arguments
    while args.len() < n_args {
        let arg_len = read_u32_le(request, idx)?;
        idx = idx.saturating_add(size_of_u32);
        let arg_end = idx.saturating_add(arg_len.try_into()?);

        println!("arg_len {:#?}", arg_len);
        println!(
            "request len: {}, idx: {}, arg_end {}",
            request.len(),
            idx,
            arg_end
        );
        let arg = request
            .get(idx..arg_end)
            .ok_or(ReadError::InvalidRange(idx, arg_end))?;
        print!("We did\n");
        idx = arg_end;
        let arg = String::from_utf8_lossy(arg);
        args.push(arg.to_string());
    }

    if idx != request.len() {
        return Err(ParseError::TrailingGarbage);
    }

    Ok(args)
}

#[derive(Debug, Default)]
struct Response {
    status: ResponseStatus,
    data: Vec<u8>,
}

#[derive(Debug, Default)]
pub enum ResponseStatus {
    #[default] ResOk = 0,
    // Error
    ResErr = 1,
    // Not found
    ResNx = 2,
}

#[derive(Debug)]
pub enum ResponseError {
    MissingArg,
}


fn handle_request(
    cmd: Vec<String>,
    g_data: &mut BTreeMap<String, String>,
) -> Result<Response, ResponseError> {
    let mut response = Response::default();

    match cmd.len() {
        2 => {
            let mut args = cmd.iter();
            let Some(arg1) = args.next() else {
                return Err(ResponseError::MissingArg);
            };

            if let Some(value) = g_data.get(arg1) {
                response.data.extend_from_slice(value.as_bytes());
            } else {
                response.status = ResponseStatus::ResNx;
            };
        }
        _ => response.status = ResponseStatus::ResErr,
    }

    Ok(response)
}

fn read_u32_le(buffer: &[u8], idx: usize) -> Result<u32, ReadError> {
    let value = u32::from_le_bytes(
        buffer
            .get(idx..idx + 4)
            .ok_or(ReadError::InvalidRange(idx, idx + 4))?
            .try_into()?,
    );
    Ok(value)
}

// Process one request if there is enough data
fn try_one_request(conn: &mut Conn, g_data: &mut BTreeMap<String, String>) -> Result<bool, ServerError> {
    let len_size = core::mem::size_of::<u32>();
    // 3. Try to parse the accumulated buffer according to the dummy protocol
    // Get message length which is a 4-byte LE integer
    if conn.incoming.len() < len_size {
        return Ok(false);
    }

    // 4. Process the parsed message
    // Read the message length
    let msg_len = usize::try_from(read_u32_le(&conn.incoming, 0)?)?;

    println!(
        "Message to read len {}, from buffer of len: {}",
        msg_len,
        conn.incoming.len()
    );

    // Protocol error
    if msg_len > MAX_KERNEL_PIPE_SIZE {
        println!("Here");
        conn.want_close = true;
        Err(ReadError::InvalidRange(0, MAX_KERNEL_PIPE_SIZE))?;
    }

    let message_end = len_size.saturating_add(msg_len);
    println!(
        "needed {} -> available {}",
        message_end,
        conn.incoming.len()
    );
    // Get the message body
    if message_end > conn.incoming.len() {
        // If we don't have enough data, we still want to read
        return Ok(false);
    }

    let request = conn
        .incoming
        .get(len_size..message_end)
        .ok_or(ReadError::InvalidRange(len_size, message_end))?;

    // If we are erroring when parsing the request, we send a signal to the event loop to close
    // the connection.
    let Ok(cmd) = parse_req(request) else {
        conn.want_close = true;
        return Ok(false);
    };

    // Fake response to not break stuff
    let response = String::new();

    // let response = String::from_utf8_lossy(&message);
    // let response = format!("hello {}", response);
    // Protocol: Length of the response first
    conn.outgoing
        .extend_from_slice(&u32::try_from(response.len())?.to_le_bytes());
    // Response afterwards
    conn.outgoing.extend_from_slice(response.as_bytes());
    // Clear the processed content leaving now the (potential) next message length starting at the
    // 0th index
    conn.incoming = conn.incoming.split_off(message_end);
    Ok(true)
}

fn handle_write(conn: &mut Conn) -> Result<(), ServerError> {
    // Check we have contents in the buffer
    if conn.outgoing.len() == 0 {
        return Ok(());
    }
    let bwritten = unsafe {
        write(
            conn.fd.try_into()?,
            conn.outgoing.as_ptr() as *const core::ffi::c_void,
            u32::try_from(conn.outgoing.len())?,
        )
    };

    // In case of optimistic non-blocking writes, the client may not be reading the response after
    // sending a request. It may try to write multiple messages first. This could cause the write
    // buffer to be full on the server-side.
    if let Err(err) = crate::check_status(bwritten) {
        if err.kind() == std::io::ErrorKind::WouldBlock {
            return Ok(());
        }
    }

    // Protocol error
    if bwritten < 0 {
        conn.want_close = true;
        return Ok(());
    }

    conn.outgoing = conn.outgoing.split_off(usize::try_from(bwritten)?);

    // If all of the data is written, we want to read next. Otherwise, we keep the want to read
    if conn.outgoing.len() == 0 {
        conn.want_read = true;
        conn.want_write = false;
    }

    Ok(())
}
